title: SizzleSupport
description: Support website for SizzleBurger
baseurl: "/"
url: https://rhysfaber.github.io/SizzleSupport

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Restaurant":
    - "https://www.roblox.com/games/576787046/SizzleBurger-Restaurant"
  "Application Center":
    - "https://www.roblox.com/games/456009291/Apply-for-a-Job-at-SizzleBurger"
  "Training Center":
    - "https://www.roblox.com/games/453839154/Training-Center"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
